q1t:
	g++ PA-4/test1.cpp -std=c++20 -o PA-4/test1.out
	./PA-4/test1.out

q2t:
	g++ PA-4/test2.cpp -std=c++20 -o PA-4/test2.out
	./PA-4/test2.out

q3t:
	g++ PA-4/test3.cpp -std=c++20 -o PA-4/test3.out
	./PA-4/test3.out $(p)

q4t:
	g++ PA-4/test4.cpp -std=c++20 -o PA-4/test4.out
	./PA-4/test4.out $(b)


q1st:
	g++ Q1/LinkedList.test.cpp -std=c++20 -o Q1/LinkedList.test.out
	

q2st:
	g++ Q2/stack.test.cpp -std=c++20 -o Q2/stack.test.out
	./Q2/stack.test.out

q3abst:
	g++ Q3/Q3a.test.cpp -std=c++20 -o Q3/Q3a.test.out
	./Q3/Q3a.test.out

q3cst:
	g++ Q3/Q3c.test.cpp -std=c++20 -o Q3/Q3c.test.out
	./Q3/Q3c.test.out


#path: personal/assignment 7/Makefile